name: Get Images

on:
  repository_dispatch:
    types: [ get-image ]
  push:
    branches:
      - master
    paths:
      - 'image-info.json'
      - 'image-list.json'
      - 'icon-info.json'
      - 'idol-info.json'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Download Image
      run: |
        pnpm install
        pnpm run get
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        commit_message: Save origin images
        target_branch: image
        build_dir: origin
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Repository Dispatch
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: replace-image
