name: Replace Images

on:
  repository_dispatch:
    types: [ replace-image ]
  push:
    branches:
      - master
    paths:
      - 'images/**'
      - 'src/**'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        path: repoMaster
    - name: Checkout origin images
      uses: actions/checkout@v2
      with:
        ref: image
        path: origin
    - name: Checkout group images
      uses: actions/checkout@v2
      with:
        repository: ShinyGroup/ShinyImage
        path: repoGroup
    - name: Move files
      run: |
        cp -r origin/ repoMaster/
        cp -r repoGroup/images/ repoMaster/
    - name: Commit changes
      run: |
        cd repoMaster
        git add --a
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "tenka"
        echo "$(git commit -m 'Update image' | tr '\n' ' ')"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
        directory: repoMaster
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Replace Image
      run: |
        cd repoMaster
        pnpm install
        pnpm run replace
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        commit_message: Save transed images
        build_dir: repoMaster/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Repository Dispatch
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: update-image